on:
  push:
    branches:
      - master
jobs:  
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        env:
          DockerUsername: ${{ secrets.DOCKER_USERNAME }}
          DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          yarn install
          yarn build:fre
          cd ./packages/react
          yarn build
          docker login -u $DockerUsername -p $DockerPassword
          docker build -t yisar/clicli_fe .
          docker push yisar/clicli_fe
  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: |
            docker pull yisar/clicli_fe
            docker-compose restart web